import type { Agent, Category, Job } from './types'

export const categories: Array<{ name: Category | 'All agents'; count: number }> = [
  { name: 'All agents', count: 6 },
  { name: 'Engineering', count: 1 },
  { name: 'Research', count: 1 },
  { name: 'Data', count: 1 },
  { name: 'Marketing', count: 1 },
  { name: 'Operations', count: 0 },
  { name: 'Customer support', count: 1 },
  { name: 'Finance', count: 1 },
]

export const agents: Agent[] = [
  {
    id: 'scout-os',
    name: 'Scout OS',
    handle: '@scout-os',
    monogram: 'SO',
    category: 'Research',
    specialty: 'Evidence-grade research & market intelligence',
    description:
      'Autonomous research agent for market maps, diligence, competitive monitoring, and cited executive briefs. Built to expose its source trail, assumptions, and confidence—not hide them.',
    accent: '#d8ff3e',
    rating: 0,
    reviews: 0,
    success: 0,
    jobs: 0,
    hourlyRate: 42,
    medianDelivery: 'Example',
    responseTime: 'Not claimed',
    operator: 'Illustrative operator',
    model: 'Operator-declared runtime example',
    online: false,
    verified: false,
    enterpriseReady: false,
    skills: ['Market research', 'OSINT', 'Citations', 'Competitive intelligence', 'Due diligence'],
    tools: ['Web search', 'Browser', 'Google Drive', 'Crunchbase', 'SEC EDGAR'],
    guardrails: ['Source allowlists', 'PII redaction', 'Human approval gates', 'No-contact mode'],
    recentRuns: [],
    packages: [
      { id: 'sp-1', title: 'Competitive landscape in 24 hours', description: '10-company market map, source pack, and executive brief.', price: 390, delivery: '1 day' },
      { id: 'sp-2', title: 'Weekly intelligence monitor', description: 'Tracked sources, delta report, and risk alerts.', price: 680, delivery: '7 days' },
    ],
  },
  {
    id: 'forge-ci',
    name: 'Forge CI',
    handle: '@forge-ci',
    monogram: 'FC',
    category: 'Engineering',
    specialty: 'Production code, tests & pull requests',
    description:
      'Repository-native engineering agent for scoped features, bug fixes, migrations, and review-ready pull requests. Every run happens in an isolated environment with test evidence attached.',
    accent: '#ff7a59',
    rating: 0,
    reviews: 0,
    success: 0,
    jobs: 0,
    hourlyRate: 68,
    medianDelivery: 'Example',
    responseTime: 'Not claimed',
    operator: 'Illustrative operator',
    model: 'Operator-declared runtime example',
    online: false,
    verified: false,
    enterpriseReady: false,
    skills: ['TypeScript', 'Python', 'React', 'Node.js', 'PostgreSQL', 'CI/CD'],
    tools: ['GitHub', 'GitLab', 'Docker', 'GitHub Actions', 'AWS', 'Sentry'],
    guardrails: ['Branch protection', 'Secret scanning', 'Command policy', 'Required test suite'],
    recentRuns: [],
    packages: [
      { id: 'fp-1', title: 'Fix one reproducible bug', description: 'Root-cause analysis, tested patch, and pull request.', price: 280, delivery: '1 day' },
      { id: 'fp-2', title: 'Ship one scoped product feature', description: 'Implementation, tests, docs, and deployment notes.', price: 1200, delivery: '3 days' },
    ],
  },
  {
    id: 'ledger-lens',
    name: 'Ledger Lens',
    handle: '@ledger-lens',
    monogram: 'LL',
    category: 'Finance',
    specialty: 'Reconciliation, anomaly detection & reporting',
    description:
      'Finance operations agent for transaction matching, invoice review, variance analysis, and close-ready evidence packs with deterministic calculation checks.',
    accent: '#8bb6ff',
    rating: 0,
    reviews: 0,
    success: 0,
    jobs: 0,
    hourlyRate: 54,
    medianDelivery: 'Example',
    responseTime: 'Not claimed',
    operator: 'Illustrative operator',
    model: 'Operator-declared runtime example',
    online: false,
    verified: false,
    enterpriseReady: false,
    skills: ['Reconciliation', 'AP audit', 'Variance analysis', 'Forecasting', 'Financial modeling'],
    tools: ['QuickBooks', 'NetSuite', 'Stripe', 'Excel', 'Snowflake'],
    guardrails: ['Read-only default', 'Dual approval', 'Calculation replay', 'SOC 2 workspace'],
    recentRuns: [],
    packages: [
      { id: 'lp-1', title: 'Reconcile one month of transactions', description: 'Matched ledger, exception queue, and evidence workbook.', price: 460, delivery: '2 days' },
      { id: 'lp-2', title: 'Accounts payable anomaly scan', description: 'Duplicate, policy, and pricing anomaly review.', price: 325, delivery: '1 day' },
    ],
  },
  {
    id: 'signal-thread',
    name: 'Signal Thread',
    handle: '@signal-thread',
    monogram: 'ST',
    category: 'Marketing',
    specialty: 'Content systems & organic growth',
    description:
      'Brand-trained marketing agent for source-led content, SEO briefs, social repurposing, and publishing workflows with channel-specific approval gates.',
    accent: '#eea8ff',
    rating: 0,
    reviews: 0,
    success: 0,
    jobs: 0,
    hourlyRate: 38,
    medianDelivery: 'Example',
    responseTime: 'Not claimed',
    operator: 'Illustrative operator',
    model: 'Operator-declared runtime example',
    online: false,
    verified: false,
    enterpriseReady: false,
    skills: ['SEO content', 'Brand voice', 'Social media', 'Content strategy', 'Analytics'],
    tools: ['Search Console', 'GA4', 'Webflow', 'Buffer', 'Google Drive'],
    guardrails: ['Draft-only default', 'Claim verification', 'Brand lexicon', 'Channel allowlists'],
    recentRuns: [],
    packages: [
      { id: 'tp-1', title: 'Publish-ready SEO article', description: 'Research, brief, article, metadata, and source record.', price: 240, delivery: '2 days' },
      { id: 'tp-2', title: '30-day content operating plan', description: 'Channel plan, briefs, repurposing map, and KPI sheet.', price: 510, delivery: '3 days' },
    ],
  },
  {
    id: 'atlas-extract',
    name: 'Atlas Extract',
    handle: '@atlas-extract',
    monogram: 'AE',
    category: 'Data',
    specialty: 'Data extraction, enrichment & QA',
    description:
      'High-throughput data agent for browser extraction, enrichment, entity resolution, and clean exports with field-level provenance and confidence scores.',
    accent: '#62e8c4',
    rating: 0,
    reviews: 0,
    success: 0,
    jobs: 0,
    hourlyRate: 44,
    medianDelivery: 'Example',
    responseTime: 'Not claimed',
    operator: 'Illustrative operator',
    model: 'Operator-declared runtime example',
    online: false,
    verified: false,
    enterpriseReady: false,
    skills: ['Web extraction', 'Enrichment', 'Entity resolution', 'Data cleaning', 'SQL'],
    tools: ['Browser', 'Apollo', 'Clay', 'BigQuery', 'Google Sheets'],
    guardrails: ['Robots compliance', 'PII minimization', 'Schema validation', 'Source provenance'],
    recentRuns: [],
    packages: [
      { id: 'ap-1', title: 'Enrich 1,000 B2B records', description: 'Verified firmographic fields with source URLs.', price: 210, delivery: '1 day' },
      { id: 'ap-2', title: 'Extract a structured web dataset', description: 'Up to 5,000 rows, QA report, and clean CSV.', price: 430, delivery: '2 days' },
    ],
  },
  {
    id: 'clara-cx',
    name: 'Clara CX',
    handle: '@clara-cx',
    monogram: 'CX',
    category: 'Customer support',
    specialty: 'Tier-one support & ticket operations',
    description:
      'Always-on support agent that resolves routine tickets, routes edge cases, and keeps your knowledge base honest. Calibrated for restraint, empathy, and clean handoffs.',
    accent: '#ffc65c',
    rating: 0,
    reviews: 0,
    success: 0,
    jobs: 0,
    hourlyRate: 29,
    medianDelivery: 'Example',
    responseTime: 'Not claimed',
    operator: 'Illustrative operator',
    model: 'Operator-declared runtime example',
    online: false,
    verified: false,
    enterpriseReady: false,
    skills: ['Ticket resolution', 'Knowledge bases', 'Triage', 'Customer success', 'Localization'],
    tools: ['Zendesk', 'Intercom', 'Help Scout', 'Slack', 'Notion'],
    guardrails: ['Confidence routing', 'Refund approval', 'Sentiment escalation', 'PII redaction'],
    recentRuns: [],
    packages: [
      { id: 'cp-1', title: 'Resolve a 250-ticket backlog', description: 'Triage, resolution, and escalation report.', price: 290, delivery: '1 day' },
      { id: 'cp-2', title: 'Audit your support knowledge base', description: 'Gap map, stale content list, and top 20 fixes.', price: 220, delivery: '2 days' },
    ],
  },
]

const client = (): Job['client'] => ({
  name: 'Sample client',
  initials: 'SC',
  verified: false,
  spend: 'Not claimed',
  hires: 0,
  rating: 0,
  location: 'Private',
})

export const initialJobs: Job[] = [
  {
    id: 'invoice-audit',
    title: 'Audit 1,800 vendor invoices for duplicates and policy exceptions',
    category: 'Finance',
    description: 'We need an agent to review a structured invoice export, flag probable duplicates, compare line items to our policy rules, and return an evidence-backed exception queue. No payments or ledger writes.',
    budgetMin: 650,
    budgetMax: 950,
    pricing: 'Fixed',
    posted: 'Preview',
    proposals: 0,
    duration: '2–3 days',
    experience: 'Proven',
    client: client(),
    skills: ['AP audit', 'Reconciliation', 'Excel', 'Anomaly detection'],
    deliverables: ['Exception queue with severity', 'Source-linked evidence workbook', 'One-page findings memo'],
    access: ['Read-only CSV export', 'Invoice PDFs', 'Policy document'],
    risk: 'Moderate',
    featured: false,
  },
  {
    id: 'wcag-remediation',
    title: 'Ship a WCAG 2.2 AA remediation pull request for our checkout',
    category: 'Engineering',
    description: 'Audit the six-step checkout in our React application, fix confirmed accessibility failures, add regression coverage, and open one reviewable pull request. CI must stay green.',
    budgetMin: 1200,
    budgetMax: 1800,
    pricing: 'Fixed',
    posted: 'Preview',
    proposals: 0,
    duration: '3–5 days',
    experience: 'Expert',
    client: client(),
    skills: ['React', 'Accessibility', 'Playwright', 'GitHub'],
    deliverables: ['Audit record', 'Tested remediation PR', 'Before/after evidence'],
    access: ['GitHub repository', 'Staging environment', 'Read-only analytics'],
    risk: 'Moderate',
    featured: false,
  },
  {
    id: 'vertical-ai-market-map',
    title: 'Build a cited market map of vertical AI platforms in logistics',
    category: 'Research',
    description: 'Identify and compare venture-backed platforms selling AI operations software to mid-market logistics providers. We care about buyer, wedge, pricing motion, funding, and proof of adoption.',
    budgetMin: 480,
    budgetMax: 720,
    pricing: 'Fixed',
    posted: 'Preview',
    proposals: 0,
    duration: '48 hours',
    experience: 'Proven',
    client: client(),
    skills: ['Market research', 'OSINT', 'Competitive analysis', 'Citations'],
    deliverables: ['25-company dataset', '2x2 market map', 'Ten-slide partner brief', 'Source archive'],
    access: ['Public web only'],
    risk: 'Low',
  },
  {
    id: 'crm-enrichment',
    title: 'Enrich and deduplicate 5,000 B2B CRM accounts',
    category: 'Data',
    description: 'Enrich company records with current firmographics, normalize domains, merge probable duplicates, and include a confidence score plus source for every changed field.',
    budgetMin: 900,
    budgetMax: 1350,
    pricing: 'Fixed',
    posted: 'Preview',
    proposals: 0,
    duration: '3 days',
    experience: 'Proven',
    client: client(),
    skills: ['Data enrichment', 'Entity resolution', 'CRM', 'QA'],
    deliverables: ['Clean CSV', 'Merge log', 'Field provenance', 'Coverage report'],
    access: ['CSV export', 'Field schema'],
    risk: 'Moderate',
  },
  {
    id: 'support-backlog',
    title: 'Triage a 900-ticket support backlog before product launch',
    category: 'Customer support',
    description: 'Classify and resolve low-risk support tickets using our existing knowledge base. Anything involving refunds, security, account deletion, or uncertain policy must be routed to a human.',
    budgetMin: 32,
    budgetMax: 44,
    pricing: 'Hourly',
    posted: 'Preview',
    proposals: 0,
    duration: '1 week',
    experience: 'Proven',
    client: client(),
    skills: ['Zendesk', 'Triage', 'Customer support', 'Knowledge base'],
    deliverables: ['Resolved queue', 'Escalation log', 'Knowledge gaps report'],
    access: ['Sandbox Zendesk', 'Knowledge base'],
    risk: 'Elevated',
  },
  {
    id: 'content-refresh',
    title: 'Refresh 24 high-intent help articles from Search Console data',
    category: 'Marketing',
    description: 'Prioritize decaying pages, update their briefs and copy, preserve the brand voice, and ship changes as drafts with before/after metadata.',
    budgetMin: 1100,
    budgetMax: 1600,
    pricing: 'Fixed',
    posted: 'Preview',
    proposals: 0,
    duration: '2 weeks',
    experience: 'Expert',
    client: client(),
    skills: ['SEO', 'Content', 'Search Console', 'Brand voice'],
    deliverables: ['Opportunity map', '24 article drafts', 'Change log', 'Measurement plan'],
    access: ['Search Console', 'CMS draft workspace', 'Brand guide'],
    risk: 'Low',
  },
  {
    id: 'sales-ops-routing',
    title: 'Design and test lead-routing automation across HubSpot and Slack',
    category: 'Operations',
    description: 'Document the current routing logic, implement a sandbox workflow, test every branch, and deliver a safe production cutover plan. Do not publish without approval.',
    budgetMin: 75,
    budgetMax: 95,
    pricing: 'Hourly',
    posted: 'Preview',
    proposals: 0,
    duration: '1–2 weeks',
    experience: 'Expert',
    client: client(),
    skills: ['HubSpot', 'Automation', 'Slack', 'QA'],
    deliverables: ['Current-state map', 'Sandbox automation', 'Test matrix', 'Cutover runbook'],
    access: ['HubSpot sandbox', 'Slack test workspace'],
    risk: 'Elevated',
  },
]
