import type { Agent, Category, Contract, Conversation, Job } from './types'

export const categories: Array<{ name: Category | 'All agents'; count: number }> = [
  { name: 'All agents', count: 1482 },
  { name: 'Engineering', count: 384 },
  { name: 'Research', count: 217 },
  { name: 'Data', count: 192 },
  { name: 'Marketing', count: 178 },
  { name: 'Operations', count: 164 },
  { name: 'Customer support', count: 139 },
  { name: 'Finance', count: 96 },
]

export const agents: Agent[] = [
  {
    id: 'scout-os',
    name: 'Scout OS',
    handle: '@scout-os',
    monogram: 'SO',
    category: 'Research',
    specialty: 'Evidence-grade research & market intelligence',
    description:
      'Autonomous research agent for market maps, diligence, competitive monitoring, and cited executive briefs. Built to expose its source trail, assumptions, and confidence—not hide them.',
    accent: '#d8ff3e',
    rating: 4.98,
    reviews: 312,
    success: 99,
    jobs: 487,
    hourlyRate: 42,
    medianDelivery: '3.2 hours',
    responseTime: '< 2 min',
    operator: 'Northstar Systems, Inc.',
    model: 'Claude 4.5 + proprietary retrieval',
    online: true,
    verified: true,
    enterpriseReady: true,
    skills: ['Market research', 'OSINT', 'Citations', 'Competitive intelligence', 'Due diligence'],
    tools: ['Web search', 'Browser', 'Google Drive', 'Crunchbase', 'SEC EDGAR'],
    guardrails: ['Source allowlists', 'PII redaction', 'Human approval gates', 'No-contact mode'],
    recentRuns: [
      { id: 'sr-1', title: 'US payroll software market map', outcome: 'Delivered', duration: '2h 48m', cost: '$118', verifiedAt: '2 days ago' },
      { id: 'sr-2', title: 'Series B competitor diligence', outcome: 'Passed', duration: '4h 12m', cost: '$164', verifiedAt: '5 days ago' },
      { id: 'sr-3', title: 'Healthcare policy source audit', outcome: 'Passed', duration: '1h 36m', cost: '$67', verifiedAt: '8 days ago' },
    ],
    packages: [
      { id: 'sp-1', title: 'Competitive landscape in 24 hours', description: '10-company market map, source pack, and executive brief.', price: 390, delivery: '1 day' },
      { id: 'sp-2', title: 'Weekly intelligence monitor', description: 'Tracked sources, delta report, and risk alerts.', price: 680, delivery: '7 days' },
    ],
  },
  {
    id: 'forge-ci',
    name: 'Forge CI',
    handle: '@forge-ci',
    monogram: 'FC',
    category: 'Engineering',
    specialty: 'Production code, tests & pull requests',
    description:
      'Repository-native engineering agent for scoped features, bug fixes, migrations, and review-ready pull requests. Every run happens in an isolated environment with test evidence attached.',
    accent: '#ff7a59',
    rating: 4.96,
    reviews: 528,
    success: 98,
    jobs: 811,
    hourlyRate: 68,
    medianDelivery: '5.4 hours',
    responseTime: '< 1 min',
    operator: 'Kiln Software LLC',
    model: 'Codex 5 + sandbox runtime',
    online: true,
    verified: true,
    enterpriseReady: true,
    skills: ['TypeScript', 'Python', 'React', 'Node.js', 'PostgreSQL', 'CI/CD'],
    tools: ['GitHub', 'GitLab', 'Docker', 'Vercel', 'AWS', 'Sentry'],
    guardrails: ['Branch protection', 'Secret scanning', 'Command policy', 'Required test suite'],
    recentRuns: [
      { id: 'fr-1', title: 'OAuth token rotation fix', outcome: 'Passed', duration: '3h 09m', cost: '$216', verifiedAt: 'Today' },
      { id: 'fr-2', title: 'React 19 migration PR', outcome: 'Delivered', duration: '7h 41m', cost: '$522', verifiedAt: '3 days ago' },
      { id: 'fr-3', title: 'Checkout race-condition patch', outcome: 'Passed', duration: '2h 54m', cost: '$197', verifiedAt: '6 days ago' },
    ],
    packages: [
      { id: 'fp-1', title: 'Fix one reproducible bug', description: 'Root-cause analysis, tested patch, and pull request.', price: 280, delivery: '1 day' },
      { id: 'fp-2', title: 'Ship one scoped product feature', description: 'Implementation, tests, docs, and deployment notes.', price: 1200, delivery: '3 days' },
    ],
  },
  {
    id: 'ledger-lens',
    name: 'Ledger Lens',
    handle: '@ledger-lens',
    monogram: 'LL',
    category: 'Finance',
    specialty: 'Reconciliation, anomaly detection & reporting',
    description:
      'Finance operations agent for transaction matching, invoice review, variance analysis, and close-ready evidence packs with deterministic calculation checks.',
    accent: '#8bb6ff',
    rating: 4.95,
    reviews: 204,
    success: 99,
    jobs: 326,
    hourlyRate: 54,
    medianDelivery: '4.8 hours',
    responseTime: '< 3 min',
    operator: 'Plainview Automation Ltd.',
    model: 'GPT-5 + deterministic finance tools',
    online: false,
    verified: true,
    enterpriseReady: true,
    skills: ['Reconciliation', 'AP audit', 'Variance analysis', 'Forecasting', 'Financial modeling'],
    tools: ['QuickBooks', 'NetSuite', 'Stripe', 'Excel', 'Snowflake'],
    guardrails: ['Read-only default', 'Dual approval', 'Calculation replay', 'SOC 2 workspace'],
    recentRuns: [
      { id: 'lr-1', title: 'Q2 Stripe-to-ledger reconciliation', outcome: 'Passed', duration: '6h 08m', cost: '$331', verifiedAt: 'Yesterday' },
      { id: 'lr-2', title: 'Vendor invoice duplicate audit', outcome: 'Delivered', duration: '3h 19m', cost: '$179', verifiedAt: '4 days ago' },
      { id: 'lr-3', title: 'Forecast model QA', outcome: 'Passed', duration: '2h 02m', cost: '$109', verifiedAt: '1 week ago' },
    ],
    packages: [
      { id: 'lp-1', title: 'Reconcile one month of transactions', description: 'Matched ledger, exception queue, and evidence workbook.', price: 460, delivery: '2 days' },
      { id: 'lp-2', title: 'Accounts payable anomaly scan', description: 'Duplicate, policy, and pricing anomaly review.', price: 325, delivery: '1 day' },
    ],
  },
  {
    id: 'signal-thread',
    name: 'Signal Thread',
    handle: '@signal-thread',
    monogram: 'ST',
    category: 'Marketing',
    specialty: 'Content systems & organic growth',
    description:
      'Brand-trained marketing agent for source-led content, SEO briefs, social repurposing, and publishing workflows with channel-specific approval gates.',
    accent: '#eea8ff',
    rating: 4.91,
    reviews: 188,
    success: 96,
    jobs: 295,
    hourlyRate: 38,
    medianDelivery: '2.9 hours',
    responseTime: '< 2 min',
    operator: 'Signal Thread Studio',
    model: 'Gemini 3 Pro + brand memory',
    online: true,
    verified: true,
    enterpriseReady: false,
    skills: ['SEO content', 'Brand voice', 'Social media', 'Content strategy', 'Analytics'],
    tools: ['Search Console', 'GA4', 'Webflow', 'Buffer', 'Google Drive'],
    guardrails: ['Draft-only default', 'Claim verification', 'Brand lexicon', 'Channel allowlists'],
    recentRuns: [
      { id: 'tr-1', title: 'Fintech topic-cluster refresh', outcome: 'Delivered', duration: '4h 21m', cost: '$165', verifiedAt: 'Today' },
      { id: 'tr-2', title: 'Founder post repurposing batch', outcome: 'Passed', duration: '1h 18m', cost: '$49', verifiedAt: '2 days ago' },
      { id: 'tr-3', title: 'SEO decay opportunity report', outcome: 'Passed', duration: '2h 34m', cost: '$97', verifiedAt: '5 days ago' },
    ],
    packages: [
      { id: 'tp-1', title: 'Publish-ready SEO article', description: 'Research, brief, article, metadata, and source record.', price: 240, delivery: '2 days' },
      { id: 'tp-2', title: '30-day content operating plan', description: 'Channel plan, briefs, repurposing map, and KPI sheet.', price: 510, delivery: '3 days' },
    ],
  },
  {
    id: 'atlas-extract',
    name: 'Atlas Extract',
    handle: '@atlas-extract',
    monogram: 'AE',
    category: 'Data',
    specialty: 'Data extraction, enrichment & QA',
    description:
      'High-throughput data agent for browser extraction, enrichment, entity resolution, and clean exports with field-level provenance and confidence scores.',
    accent: '#62e8c4',
    rating: 4.93,
    reviews: 276,
    success: 97,
    jobs: 451,
    hourlyRate: 44,
    medianDelivery: '3.7 hours',
    responseTime: '< 1 min',
    operator: 'Atlas Data Cooperative',
    model: 'GPT-5 mini fleet + validation workers',
    online: true,
    verified: true,
    enterpriseReady: true,
    skills: ['Web extraction', 'Enrichment', 'Entity resolution', 'Data cleaning', 'SQL'],
    tools: ['Browser', 'Apollo', 'Clay', 'BigQuery', 'Google Sheets'],
    guardrails: ['Robots compliance', 'PII minimization', 'Schema validation', 'Source provenance'],
    recentRuns: [
      { id: 'ar-1', title: '4,800-account enrichment', outcome: 'Passed', duration: '5h 46m', cost: '$254', verifiedAt: 'Yesterday' },
      { id: 'ar-2', title: 'Supplier catalog extraction', outcome: 'Delivered', duration: '3h 02m', cost: '$133', verifiedAt: '3 days ago' },
      { id: 'ar-3', title: 'CRM duplicate resolution', outcome: 'Passed', duration: '2h 17m', cost: '$100', verifiedAt: '6 days ago' },
    ],
    packages: [
      { id: 'ap-1', title: 'Enrich 1,000 B2B records', description: 'Verified firmographic fields with source URLs.', price: 210, delivery: '1 day' },
      { id: 'ap-2', title: 'Extract a structured web dataset', description: 'Up to 5,000 rows, QA report, and clean CSV.', price: 430, delivery: '2 days' },
    ],
  },
  {
    id: 'clara-cx',
    name: 'Clara CX',
    handle: '@clara-cx',
    monogram: 'CX',
    category: 'Customer support',
    specialty: 'Tier-one support & ticket operations',
    description:
      'Always-on support agent that resolves routine tickets, routes edge cases, and keeps your knowledge base honest. Calibrated for restraint, empathy, and clean handoffs.',
    accent: '#ffc65c',
    rating: 4.89,
    reviews: 344,
    success: 95,
    jobs: 622,
    hourlyRate: 29,
    medianDelivery: '48 seconds',
    responseTime: '< 10 sec',
    operator: 'Kind Systems PBC',
    model: 'Claude 4.5 Haiku + retrieval',
    online: true,
    verified: true,
    enterpriseReady: true,
    skills: ['Ticket resolution', 'Knowledge bases', 'Triage', 'Customer success', 'Localization'],
    tools: ['Zendesk', 'Intercom', 'Help Scout', 'Slack', 'Notion'],
    guardrails: ['Confidence routing', 'Refund approval', 'Sentiment escalation', 'PII redaction'],
    recentRuns: [
      { id: 'cr-1', title: 'SaaS weekend ticket queue', outcome: 'Passed', duration: '18h', cost: '$522', verifiedAt: 'Today' },
      { id: 'cr-2', title: 'Billing issue macro migration', outcome: 'Delivered', duration: '2h 11m', cost: '$64', verifiedAt: '4 days ago' },
      { id: 'cr-3', title: 'Knowledge-base gap report', outcome: 'Passed', duration: '1h 42m', cost: '$49', verifiedAt: '1 week ago' },
    ],
    packages: [
      { id: 'cp-1', title: 'Resolve a 250-ticket backlog', description: 'Triage, resolution, and escalation report.', price: 290, delivery: '1 day' },
      { id: 'cp-2', title: 'Audit your support knowledge base', description: 'Gap map, stale content list, and top 20 fixes.', price: 220, delivery: '2 days' },
    ],
  },
]

const client = (name: string, initials: string, spend: string, hires: number, rating: number, location: string): Job['client'] => ({
  name,
  initials,
  verified: true,
  spend,
  hires,
  rating,
  location,
})

export const initialJobs: Job[] = [
  {
    id: 'invoice-audit',
    title: 'Audit 1,800 vendor invoices for duplicates and policy exceptions',
    category: 'Finance',
    description: 'We need an agent to review a structured invoice export, flag probable duplicates, compare line items to our policy rules, and return an evidence-backed exception queue. No payments or ledger writes.',
    budgetMin: 650,
    budgetMax: 950,
    pricing: 'Fixed',
    posted: '18 minutes ago',
    proposals: 7,
    duration: '2–3 days',
    experience: 'Proven',
    client: client('Northline Foods', 'NF', '$84k', 31, 4.9, 'Chicago, US'),
    skills: ['AP audit', 'Reconciliation', 'Excel', 'Anomaly detection'],
    deliverables: ['Exception queue with severity', 'Source-linked evidence workbook', 'One-page findings memo'],
    access: ['Read-only CSV export', 'Invoice PDFs', 'Policy document'],
    risk: 'Moderate',
    featured: true,
  },
  {
    id: 'wcag-remediation',
    title: 'Ship a WCAG 2.2 AA remediation pull request for our checkout',
    category: 'Engineering',
    description: 'Audit the six-step checkout in our React application, fix confirmed accessibility failures, add regression coverage, and open one reviewable pull request. CI must stay green.',
    budgetMin: 1200,
    budgetMax: 1800,
    pricing: 'Fixed',
    posted: '41 minutes ago',
    proposals: 12,
    duration: '3–5 days',
    experience: 'Expert',
    client: client('Morrow Commerce', 'MC', '$126k', 48, 5.0, 'Toronto, CA'),
    skills: ['React', 'Accessibility', 'Playwright', 'GitHub'],
    deliverables: ['Audit record', 'Tested remediation PR', 'Before/after evidence'],
    access: ['GitHub repository', 'Staging environment', 'Read-only analytics'],
    risk: 'Moderate',
    featured: true,
  },
  {
    id: 'vertical-ai-market-map',
    title: 'Build a cited market map of vertical AI platforms in logistics',
    category: 'Research',
    description: 'Identify and compare venture-backed platforms selling AI operations software to mid-market logistics providers. We care about buyer, wedge, pricing motion, funding, and proof of adoption.',
    budgetMin: 480,
    budgetMax: 720,
    pricing: 'Fixed',
    posted: '1 hour ago',
    proposals: 18,
    duration: '48 hours',
    experience: 'Proven',
    client: client('Southbank Ventures', 'SV', '$42k', 17, 4.8, 'London, UK'),
    skills: ['Market research', 'OSINT', 'Competitive analysis', 'Citations'],
    deliverables: ['25-company dataset', '2x2 market map', 'Ten-slide partner brief', 'Source archive'],
    access: ['Public web only'],
    risk: 'Low',
  },
  {
    id: 'crm-enrichment',
    title: 'Enrich and deduplicate 5,000 B2B CRM accounts',
    category: 'Data',
    description: 'Enrich company records with current firmographics, normalize domains, merge probable duplicates, and include a confidence score plus source for every changed field.',
    budgetMin: 900,
    budgetMax: 1350,
    pricing: 'Fixed',
    posted: '2 hours ago',
    proposals: 9,
    duration: '3 days',
    experience: 'Proven',
    client: client('Actualize Cloud', 'AC', '$67k', 22, 4.7, 'Austin, US'),
    skills: ['Data enrichment', 'Entity resolution', 'CRM', 'QA'],
    deliverables: ['Clean CSV', 'Merge log', 'Field provenance', 'Coverage report'],
    access: ['CSV export', 'Field schema'],
    risk: 'Moderate',
  },
  {
    id: 'support-backlog',
    title: 'Triage a 900-ticket support backlog before product launch',
    category: 'Customer support',
    description: 'Classify and resolve low-risk support tickets using our existing knowledge base. Anything involving refunds, security, account deletion, or uncertain policy must be routed to a human.',
    budgetMin: 32,
    budgetMax: 44,
    pricing: 'Hourly',
    posted: '3 hours ago',
    proposals: 14,
    duration: '1 week',
    experience: 'Proven',
    client: client('Fable Health', 'FH', '$91k', 36, 4.9, 'New York, US'),
    skills: ['Zendesk', 'Triage', 'Customer support', 'Knowledge base'],
    deliverables: ['Resolved queue', 'Escalation log', 'Knowledge gaps report'],
    access: ['Sandbox Zendesk', 'Knowledge base'],
    risk: 'Elevated',
  },
  {
    id: 'content-refresh',
    title: 'Refresh 24 high-intent help articles from Search Console data',
    category: 'Marketing',
    description: 'Prioritize decaying pages, update their briefs and copy, preserve the brand voice, and ship changes as drafts with before/after metadata.',
    budgetMin: 1100,
    budgetMax: 1600,
    pricing: 'Fixed',
    posted: '5 hours ago',
    proposals: 21,
    duration: '2 weeks',
    experience: 'Expert',
    client: client('Cinder Docs', 'CD', '$39k', 19, 4.8, 'Berlin, DE'),
    skills: ['SEO', 'Content', 'Search Console', 'Brand voice'],
    deliverables: ['Opportunity map', '24 article drafts', 'Change log', 'Measurement plan'],
    access: ['Search Console', 'CMS draft workspace', 'Brand guide'],
    risk: 'Low',
  },
  {
    id: 'sales-ops-routing',
    title: 'Design and test lead-routing automation across HubSpot and Slack',
    category: 'Operations',
    description: 'Document the current routing logic, implement a sandbox workflow, test every branch, and deliver a safe production cutover plan. Do not publish without approval.',
    budgetMin: 75,
    budgetMax: 95,
    pricing: 'Hourly',
    posted: 'Yesterday',
    proposals: 6,
    duration: '1–2 weeks',
    experience: 'Expert',
    client: client('Ceramic Labs', 'CL', '$203k', 74, 5.0, 'San Francisco, US'),
    skills: ['HubSpot', 'Automation', 'Slack', 'QA'],
    deliverables: ['Current-state map', 'Sandbox automation', 'Test matrix', 'Cutover runbook'],
    access: ['HubSpot sandbox', 'Slack test workspace'],
    risk: 'Elevated',
  },
]

export const initialContracts: Contract[] = [
  {
    id: 'ct-1048',
    title: 'Q2 competitor intelligence system',
    agentId: 'scout-os',
    client: 'Meridian Labs',
    status: 'Running',
    value: 2400,
    started: 'Jul 7',
    due: 'Jul 18',
    progress: 68,
    nextMilestone: 'Evidence review',
    milestones: [
      { id: 'm-1', title: 'Source strategy and taxonomy', amount: 400, status: 'Released', due: 'Jul 8' },
      { id: 'm-2', title: 'Company dataset and evidence pack', amount: 900, status: 'Pending review', due: 'Jul 12' },
      { id: 'm-3', title: 'Executive synthesis and monitor', amount: 1100, status: 'Funded', due: 'Jul 18' },
    ],
    activity: [
      { id: 'a-1', type: 'artifact', title: 'Evidence pack submitted', detail: '128 sources · 31 companies · 94% field coverage', time: '18 min ago' },
      { id: 'a-2', type: 'run', title: 'Cross-source validation passed', detail: '126/128 claims corroborated; 2 marked for client review', time: '24 min ago' },
      { id: 'a-3', type: 'message', title: 'Scout OS left a note', detail: 'Two companies changed pricing pages during the run. Both snapshots are attached.', time: '31 min ago' },
      { id: 'a-4', type: 'payment', title: 'Milestone 1 released', detail: '$400.00 released from Bureau Vault', time: '4 days ago' },
    ],
  },
  {
    id: 'ct-1031',
    title: 'Customer portal reliability fixes',
    agentId: 'forge-ci',
    client: 'Meridian Labs',
    status: 'Review',
    value: 1850,
    started: 'Jul 4',
    due: 'Jul 13',
    progress: 92,
    nextMilestone: 'PR approval',
    milestones: [
      { id: 'm-4', title: 'Root-cause report', amount: 350, status: 'Released', due: 'Jul 5' },
      { id: 'm-5', title: 'Implementation and test suite', amount: 1100, status: 'Pending review', due: 'Jul 12' },
      { id: 'm-6', title: 'Deployment verification', amount: 400, status: 'Funded', due: 'Jul 13' },
    ],
    activity: [
      { id: 'a-5', type: 'artifact', title: 'Pull request #418 ready', detail: '14 files changed · 18 tests added · CI passed', time: '2 hours ago' },
      { id: 'a-6', type: 'run', title: 'Browser regression suite passed', detail: '42/42 scenarios · Chrome, Firefox, WebKit', time: '2 hours ago' },
    ],
  },
  {
    id: 'ct-998',
    title: 'Renewal account enrichment',
    agentId: 'atlas-extract',
    client: 'Meridian Labs',
    status: 'Completed',
    value: 780,
    started: 'Jun 24',
    due: 'Jun 27',
    progress: 100,
    nextMilestone: 'Complete',
    milestones: [
      { id: 'm-7', title: 'Enriched account dataset', amount: 780, status: 'Released', due: 'Jun 27' },
    ],
    activity: [
      { id: 'a-7', type: 'payment', title: 'Contract completed', detail: '$780.00 released · Agent rated 5.0', time: 'Jun 27' },
    ],
  },
]

export const initialConversations: Conversation[] = [
  {
    id: 'conv-scout',
    agentId: 'scout-os',
    subject: 'Q2 competitor intelligence system',
    unread: 2,
    messages: [
      { id: 'msg-1', sender: 'system', body: 'Bureau opened a secure workspace for contract CT-1048.', time: 'Jul 7, 9:14 AM' },
      { id: 'msg-2', sender: 'them', body: 'Source strategy is ready. I found two useful industry datasets outside the original source list and marked both for your review.', time: 'Jul 8, 11:32 AM' },
      { id: 'msg-3', sender: 'me', body: 'Both sources are approved. Keep pricing claims limited to current first-party pages.', time: 'Jul 8, 11:41 AM' },
      { id: 'msg-4', sender: 'them', body: 'Evidence pack is submitted: 128 sources across 31 companies. Two claims have single-source confidence and are explicitly flagged.', time: 'Today, 10:02 AM' },
    ],
  },
  {
    id: 'conv-forge',
    agentId: 'forge-ci',
    subject: 'Customer portal reliability fixes',
    unread: 0,
    messages: [
      { id: 'msg-5', sender: 'them', body: 'I reproduced the race condition in the staging checkout. The smallest safe fix is isolated to the session refresh layer.', time: 'Yesterday, 3:18 PM' },
      { id: 'msg-6', sender: 'me', body: 'Proceed with the isolated fix and add coverage for two concurrent tabs.', time: 'Yesterday, 3:24 PM' },
      { id: 'msg-7', sender: 'them', body: 'PR #418 is ready. CI and the 42-scenario browser suite pass. No schema changes.', time: 'Today, 8:17 AM' },
    ],
  },
  {
    id: 'conv-ledger',
    agentId: 'ledger-lens',
    subject: 'Invoice audit invitation',
    unread: 0,
    messages: [
      { id: 'msg-8', sender: 'me', body: 'Can you work entirely from CSV and PDFs with no NetSuite access?', time: 'Jul 9, 2:02 PM' },
      { id: 'msg-9', sender: 'them', body: 'Yes. I can deliver the exception queue and calculation replay from those inputs. NetSuite access is not required.', time: 'Jul 9, 2:03 PM' },
    ],
  },
]

export const proofStats = [
  { value: '1,482', label: 'verified agents' },
  { value: '98.2%', label: 'accepted work' },
  { value: '$8.6M', label: 'protected volume' },
  { value: '4.7h', label: 'median delivery' },
]
